Models/Revista.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System;

namespace Amigurumis.Models
{
    [Table("Revista")]
    public class Revista
    {

        public Revista()
        {
            this.VReceita = new HashSet<Receita>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [MaxLength(100)]
        public string Tema { get; set; }
        [Required]
        public int NumeroEdicao { get; set; }
     
        public byte[] FotoCapa { get; set; }

        public virtual ICollection<Receita> VReceita { get; set; }
    }
}

Controllers/RevistasController.cs
using Amigurumis.Models;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Amigurumis.Controllers
{
    public class RevistasController : Controller
    {
        private AmigurumisContext db = new AmigurumisContext();

        // GET: Revistas
        public ActionResult Index()
        {
            return View(db.REVISTAS.ToList());
        }

        // desserializando a imagem 
        public FileContentResult getImagem(int id)
        {
            byte[] byteArray = db.REVISTAS.Find(id).FotoCapa;
            return byteArray != null
                ? new FileContentResult(byteArray, "image/jpeg")
                : null;
        }


        // GET: Revistas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Revista revista = db.REVISTAS.Find(id);
            if (revista == null)
            {
                return HttpNotFound();
            }
            return View(revista);
        }

        // GET: Revistas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Revistas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Tema,NumeroEdicao,FotoCapa")] Revista revista, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
               
                    if (file.FileName != null)
                    {
                        MemoryStream target = new MemoryStream();
                        file.InputStream.CopyTo(target);
                        byte[] data = target.ToArray();
                        revista.FotoCapa = data;
                    }
                    db.REVISTAS.Add(revista);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                
               

            }

            return View(revista);
        }

        // GET: Revistas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Revista revista = db.REVISTAS.Find(id);
            if (revista == null)
            {
                return HttpNotFound();
            }
            return View(revista);
        }

        // POST: Revistas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Tema,NumeroEdicao,FotoCapa")] Revista revista, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file.FileName != null)
                {
                    MemoryStream target = new MemoryStream();
                    file.InputStream.CopyTo(target);
                    byte[] data = target.ToArray();
                    revista.FotoCapa = data;
                }
                db.Entry(revista).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(revista);
        }

        // GET: Revistas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Revista revista = db.REVISTAS.Find(id);
            if (revista == null)
            {
                return HttpNotFound();
            }
            return View(revista);
        }

        // POST: Revistas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Revista revista = db.REVISTAS.Find(id);
            db.REVISTAS.Remove(revista);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Revistas/Create.cshtml
@model Amigurumis.Models.Revista

@{
    ViewBag.Title = "Cadastro";
}

<h2>Cadastrar Revista</h2>
<br />

@using (Html.BeginForm("Create", "Revistas", FormMethod.Post, new { enctype = "multipart/form-data" }))

{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Revista</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Tema:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tema, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tema, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Número Edição:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumeroEdicao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumeroEdicao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Foto de Capa:", htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                <br />
                <div>
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" id="file" aria-describedby="inputGroupFileAddon01"
                               name="file" required>
                        @Html.ValidationMessageFor(model => model.NumeroEdicao, "", new { @class = "text-danger" })
                        <label class="custom-file-label" for="inputGroupFile01">Selecionar...</label>
                    </div>
                </div>
            </div>

        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cadastrar" class="btn btn-success" />
            </div>
        </div>
    </div>
    <script src="~/Views/MsgErro/errosMsg.js"></script>
}

<div>
    @Html.ActionLink("Retornar para Listagem", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}

Views/Revistas/Delete.cshtml
@model Amigurumis.Models.Revista

@{
    ViewBag.Title = "Excluir";
}

<h2>Excluir</h2>

<h3>Confirma a Exclusão do registro ?</h3>
<div>
    <br /><br />
    <h4>Revista</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.Label("Tema:")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tema)
        </dd>

        <dt>
            @Html.Label("Número Edição:")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumeroEdicao)
        </dd>

        <dt>
            @Html.Label("Foto da Capa:")
        </dt>

        <dd>
            <div style="padding-top: 10px;">
                <div>
                    <img src="@Url.Action("getImagem", "Revistas", new { id = Model.Id })" alt="Foto de Capa da Revista" />
                </div>
            </div>
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-danger" /><br /><br /><br />
            @Html.ActionLink("Retornar para a Listagem", "Index")
        </div>
    }
</div>

Views/Revistas/Details.cshtml
@model Amigurumis.Models.Revista

@{
    ViewBag.Title = "Detalhes";
}

<h2>Detalhes</h2>

<div>
    <h4>Revista</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.Label("Tema:")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tema)
        </dd>

        <dt>
            @Html.Label("Número da Edição:")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumeroEdicao)
        </dd>

        <dt>
            @Html.Label("Foto da Capa:")
        </dt>

        <dd>
            <div style="padding-top: 10px;">
                <div>
                    <img src="@Url.Action("getImagem", "Revistas", new { id = Model.Id })" alt="Foto de Capa da Revista" />
                </div>
            </div>
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id })  |
    @Html.ActionLink("Retornar para Listagem", "Index")
</p>

Views/Revistas/Edit.cshtml
@model Amigurumis.Models.Revista

@{
    ViewBag.Title = "Editar";
}

<h2>Editar Revista</h2>


@using (Html.BeginForm("Edit", "Revistas", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Revista</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.Label("Tema:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tema, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tema, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Número da Edição:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumeroEdicao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumeroEdicao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Foto da Capa:", htmlAttributes: new { @class = "control-label col-md-2" })
            
            <div class="col-md-10">
                <img src="@Url.Action("getImagem", "Revistas", new { id = Model.Id })" alt="Foto de Capa da Revista" />
                
                <div style="padding-top:15px;">
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" id="file" aria-describedby="inputGroupFileAddon01" name="file">
                        <label class="custom-file-label" for="inputGroupFile01">Selecionar...</label>
                    </div>
                </div>
            </div>

        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Savar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retornar para Listagem", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Revistas/Index.cshtml
@model IEnumerable<Amigurumis.Models.Revista>

@{
    ViewBag.Title = "Listagem";
}

    <h2>Listagem de Revistas</h2>
    <br />
<p>
    @Html.ActionLink("Cadastrar", "Create")
</p>
<br />
<table class="table">
    <tr>
        <th>
            @Html.Label("Tema")
        </th>
        <th>
            @Html.Label("Número da Edição")
        </th>
        <th>
            @Html.Label("Foto da Capa")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Tema)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NumeroEdicao)
        </td>
        <td>
            <div class="col-md-10" style="border: thin; padding-top: 10px;">
                <div>
                    <img src="@Url.Action("getImagem", "Revistas", new { id = item.Id })" alt="Foto de Capa da Revista" style="width: 120px; height: 160px" />
                </div>
            </div>
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Detalhes", "Details", new { id = item.Id }) |
            @Html.ActionLink("Excluir", "Delete", new { id = item.Id })
        </td>
    </tr>
}

</table>